[package]
name = "rustBase"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
futures = "0.3" 

[dev-dependencies]
